# This starter workflow is for a CMake project running on multiple platforms.
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64 gcc Release
          - runner: ubuntu-latest
            os: ubuntu
            arch: x86_64
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release
            
          # Linux x86_64 clang Release  
          - runner: ubuntu-latest
            os: ubuntu
            arch: x86_64
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Release

          # Windows x86_64 MSVC Release
          - runner: windows-latest
            os: windows
            arch: x86_64
            c_compiler: cl
            cpp_compiler: cl
            build_type: Release

          # macOS Intel x86_64 Release
          - runner: macos-13
            os: macos
            arch: x86_64
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Release

          # macOS ARM64 Release
          - runner: macos-14
            os: macos
            arch: arm64
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Release

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        cmake \
        build-essential \
        libasound2-dev \
        libjack-jackd2-dev \
        libfltk1.3-dev \
        gettext

    - name: Setup vcpkg with cache
      if: runner.os == 'Windows'
      uses: lukka/run-vcpkg@v11
      env:
        VCPKG_ROOT: C:\vcpkg
        VCPKG_TARGET_TRIPLET: x64-windows
      with:
        vcpkgDirectory: ${{ github.workspace }}/vcpkg
        vcpkgArgs: install
        cache: true

    - name: Install FLTK (Windows)
      if: matrix.os == 'windows'
      shell: powershell
      run: |
        .\vcpkg\vcpkg install fltk:x64-windows
        
    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DARCH=${{ matrix.arch }}
        -S ${{ github.workspace }}

    - name: Build
      # Build avec --config SEULEMENT sur Windows
      run: |
        if [ "${{ matrix.os }}" = "windows" ]; then
          cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
        else
          cmake --build ${{ steps.strings.outputs.build-output-dir }}
        fi
        
    - name: Package tar.gz
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      shell: bash
      run: |
        cpack -G TGZ
        mkdir -p ../release
        mv FreeMajor-1.0.1-* FreeMajor-1.0.1.tar.gz
        cp FreeMajor-1.0.1.tar.gz ../release/
      if: runner.os == 'Linux'

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        if [ "${{ matrix.os }}" = "windows" ]; then
          ctest --build-config ${{ matrix.build_type }}
        else
          ctest
        fi

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config ${{ matrix.build_type }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download source tar.gz
        uses: actions/download-artifact@v4
        with:
          path: ./release
          pattern: FreeMajor-1.0.1*

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: automatic
          prerelease: true
          files: |
            release/FreeMajor-1.0.1-Linux.tar.gz
            release/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}